// generated by gmod
package main

import (
	"fmt"
	"os"
	"os/user"

	"github.com/NishanthSpShetty/monkey/repl"
)

func main() {
	user, err := user.Current()
	if err != nil {
		panic(err)
	}

	fmt.Printf("Hello %s! This is monkey lang\n", user.Username)
	repl.Start(os.Stdin, os.Stdout)
}
